In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("../data/retail_store_inventory.csv")

In [4]:
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer

In [5]:
df.shape

(73100, 15)

In [6]:
df.columns

Index(['Date', 'Store ID', 'Product ID', 'Category', 'Region',
       'Inventory Level', 'Units Sold', 'Units Ordered', 'Demand Forecast',
       'Price', 'Discount', 'Weather Condition', 'Holiday/Promotion',
       'Competitor Pricing', 'Seasonality'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 73100 entries, 0 to 73099
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                73100 non-null  str
 1   Store ID            73100 non-null  str
 2   Product ID          73100 non-null  str
 3   Category            73100 non-null  str
 4   Region              73100 non-null  str
 5   Inventory Level     73100 non-null  int64
 6   Units Sold          73100 non-null  int64
 7   Units Ordered       73100 non-null  int64
 8   Demand Forecast     73100 non-null  float64
 9   Price               73100 non-null  float64
 10  Discount            73100 non-null  int64
 11  Weather Condition   73100 non-null  str
 12  Holiday/Promotion   73100 non-null  int64
 13  Competitor Pricing  73100 non-null  float64
 14  Seasonality         73100 non-null  str
dtypes: float64(3), int64(5), str(7)
memory usage: 8.4 MB

In [8]:
df.isnull().sum()

Date                  0
Store ID              0
Product ID            0
Category              0
Region                0
Inventory Level       0
Units Sold            0
Units Ordered         0
Demand Forecast       0
Price                 0
Discount              0
Weather Condition     0
Holiday/Promotion     0
Competitor Pricing    0
Seasonality           0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df["Date"].dtype

In [11]:
df["Date"] = pd.to_datetime(df["Date"])

In [12]:
df.describe()

,Date,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Holiday/Promotion,Competitor Pricing
count,73100,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000
mean,2023-01-01 00:00:00,274.469877,136.464870,110.004473,141.494720,55.135108,10.009508,0.497305,55.146077
min,2022-01-01 00:00:00,50.000000,0.000000,20.000000,-9.990000,10.000000,0.000000,0.000000,5.030000
25%,2022-07-02 00:00:00,162.000000,49.000000,65.000000,53.670000,32.650000,5.000000,0.000000,32.680000
50%,2023-01-01 00:00:00,273.000000,107.000000,110.000000,113.015000,55.050000,10.000000,0.000000,55.010000
75%,2023-07-03 00:00:00,387.000000,203.000000,155.000000,208.052500,77.860000,15.000000,1.000000,77.820000
max,2024-01-01 00:00:00,500.000000,499.000000,200.000000,518.550000,100.000000,20.000000,1.000000,104.940000
std,NaN,129.949514,108.919406,52.277448,109.254076,26.021945,7.083746,0.499996,26.191408

In [14]:
df[df["Demand Forecast"] < 0].shape

(673, 15)

In [15]:
df_clean = df[df["Demand Forecast"] >= 0].copy()

In [16]:
df_clean.shape

(72427, 15)

In [17]:
df_clean[df_clean["Demand Forecast"] < 0].shape

(0, 15)

In [18]:
df_clean["Category"].value_counts()

Category
Furniture      14570
Toys           14503
Clothing       14494
Groceries      14468
Electronics    14392
Name: count, dtype: int64

In [19]:
df_clean["Region"].value_counts()

Region
East     18157
South    18148
North    18063
West     18059
Name: count, dtype: int64

In [20]:
df_clean["Weather Condition"].value_counts()

Weather Condition
Rainy     18120
Sunny     18112
Cloudy    18099
Snowy     18096
Name: count, dtype: int64

In [21]:
df_clean["Seasonality"].value_counts()

Seasonality
Summer    18133
Winter    18129
Spring    18125
Autumn    18040
Name: count, dtype: int64

In [22]:
df_clean["Units Sold"].sum()

np.int64(9973622)

In [23]:
df_clean["Units Ordered"].sum()

np.int64(7968374)

In [24]:
df_clean["Inventory Level"].mean()

np.float64(275.16509036685216)

In [25]:
df_clean["Demand Forecast"].mean()

np.float64(142.84382785425325)

In [26]:
df_clean["Inventory Coverage"] = (
    df_clean["Inventory Level"] / df_clean["Demand Forecast"]
)

In [27]:
df_clean[[
    "Store ID",
    "Product ID",
    "Inventory Level",
    "Demand Forecast",
    "Inventory Coverage"
]].head(10)

  Store ID Product ID  Inventory Level  Demand Forecast  Inventory Coverage
0     S001      P0001              231           135.47            1.705175
1     S001      P0002              204           144.04            1.416273
2     S001      P0003              102            74.02            1.378006
3     S001      P0004              469            62.18            7.542618
4     S001      P0005              166             9.26           17.926566
5     S001      P0006              138           139.82            0.986983
6     S001      P0007              359           108.92            3.295997
7     S001      P0008              380           329.73            1.152458
8     S001      P0009              183           174.15            1.050818
9     S001      P0010              108            24.47            4.413568

In [28]:
df_clean["Inventory Coverage"].describe()

count    72427.000000
mean         6.687217
std        130.407933
min          0.729718
25%          1.287792
50%          1.903226
75%          3.568473
max      22300.000000
Name: Inventory Coverage, dtype: float64

In [29]:
(df_clean["Demand Forecast"] < 0.05).sum()

np.int64(4)

In [31]:
category_sales = (
    df_clean.groupby("Category")["Units Sold"]
    .sum()
    .sort_values(ascending=False)
)

category_sales

Category
Furniture      2024604
Groceries      2000076
Clothing       1998818
Toys           1990075
Electronics    1960049
Name: Units Sold, dtype: int64

In [32]:
category_inventory = (
    df_clean.groupby("Category")["Inventory Level"]
    .mean()
    .sort_values(ascending=False)
)

category_inventory

Category
Groceries      276.616257
Furniture      276.431640
Clothing       275.336484
Toys           274.230228
Electronics    273.193510
Name: Inventory Level, dtype: float64

In [33]:
category_coverage = (
    df_clean.groupby("Category")["Inventory Coverage"]
    .median()
    .sort_values(ascending=False)
)

category_coverage

Category
Electronics    1.915101
Clothing       1.904385
Groceries      1.903221
Furniture      1.902173
Toys           1.891794
Name: Inventory Coverage, dtype: float64

In [34]:
store_coverage = (
    df_clean.groupby("Store ID")["Inventory Coverage"]
    .median()
    .sort_values()
)

store_coverage.head(10)

Store ID
S003    1.889723
S004    1.895329
S002    1.908793
S001    1.910828
S005    1.914139
Name: Inventory Coverage, dtype: float64

In [35]:
low_coverage = df_clean[df_clean["Inventory Coverage"] < 1]

low_coverage.shape

(2585, 16)

In [36]:
low_coverage_by_category = (
    low_coverage.groupby("Category")
    .size()
    .sort_values(ascending=False)
)

low_coverage_by_category

Category
Groceries      535
Furniture      524
Clothing       510
Electronics    508
Toys           508
dtype: int64

In [37]:
low_coverage_pct = (
    df_clean.groupby("Category")["Inventory Coverage"]
    .apply(lambda x: (x < 1).mean() * 100)
    .sort_values(ascending=False)
)

low_coverage_pct

Category
Groceries      3.697816
Furniture      3.596431
Electronics    3.529739
Clothing       3.518697
Toys           3.502724
Name: Inventory Coverage, dtype: float64

In [38]:
product_pressure = (
    low_coverage.groupby("Product ID")
    .size()
    .sort_values(ascending=False)
)

product_pressure.head(10)

Product ID
P0004    149
P0019    146
P0013    143
P0010    141
P0009    140
P0008    138
P0020    130
P0003    129
P0002    128
P0011    127
dtype: int64

In [39]:
product_pressure_pct = (
    df_clean.groupby("Product ID")["Inventory Coverage"]
    .apply(lambda x: (x < 1).mean() * 100)
    .sort_values(ascending=False)
)

product_pressure_pct.head(10)

Product ID
P0004    4.118297
P0019    4.049931
P0013    3.947005
P0010    3.898258
P0009    3.864201
P0008    3.810050
P0020    3.591160
P0003    3.565506
P0002    3.533959
P0007    3.510227
Name: Inventory Coverage, dtype: float64

In [40]:
df_clean.to_csv("../data/retail_inventory_clean.csv", index=False)

In [42]:
import os

os.path.exists("../data/retail_inventory_clean.csv")

True